export { default as Admin } from './admin/Admin'
export { default as Cart } from './cart/Cart'
export { default as Favorites } from './favorites/Favorites'
export { default as Home } from './home/Home'
export { default as Login } from './login/Login'
export { default as NotFound } from './not-found/NotFound'
export { default as ProtectedRoute } from './protect-route/ProtectedRoute'
export { default as SingleRoute } from './single-route/SingleRoute'
